### ISSUE TITLE
[V9.0 Windows] not working

### ISSUE THREAD

**Issue by XPower7125** [Baracchino-Della-Scuola/DiSH#3]
![image](https://user-images.githubusercontent.com/64551044/206868879-acbd59f2-4f84-4abb-bf70-06c693444ae9.png)

**Comment by StarNumber12046** [comment]
it seems to be caused by logging. I reverted it in last commit.
We don't need logs :/

**Comment by XPower7125** [comment]
looks like it's fixed in the latest beta
